### ISSUE TITLE
How to embed SERA in XGBoost

### ISSUE THREAD

**Issue by spree1010** [nunompmoniz/IRon#1]
Hi,  after reading the document I want to have a try of IRon packackge to XGBoost, but I am not quite familiar with XGBoost,  would you please suggest how to embed SERA in XGBoost, is there any sample code?

Thank you very much!
Kun

**Comment by nunompmoniz** [comment]
Hello! 
My student is right now finishing his thesis on that same subject. 
He has a repository (below) where you can find the code to implement SERA as an optimization metric, tested with gradient boosting.
https://github.com/anibalsilva1/ModelOptimizationIR
Also, the paper: https://arxiv.org/abs/2206.09991
